package model;

import model.common.AppModule;

import oracle.adf.model.BindingContext;

import oracle.binding.BindingContainer;
import oracle.binding.OperationBinding;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 03 11:40:45 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentsVO1.
     * @return DepartmentsVO1
     */
    public ViewObjectImpl getDepartmentsVO1() {
        return (ViewObjectImpl) findViewObject("DepartmentsVO1");
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public ViewObjectImpl getEmployeesVO1() {
        return (ViewObjectImpl) findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for EmployeesVO2.
     * @return EmployeesVO2
     */
    public ViewObjectImpl getEmployeesVO2() {
        return (ViewObjectImpl) findViewObject("EmployeesVO2");
    }

    /**
     * Container's getter for EmployeesVO3.
     * @return EmployeesVO3
     */
    public ViewObjectImpl getEmployeesVO3() {
        return (ViewObjectImpl) findViewObject("EmployeesVO3");
    }

    /**
     * Container's getter for DepartmentsVO2.
     * @return DepartmentsVO2
     */
    public ViewObjectImpl getDepartmentsVO2() {
        return (ViewObjectImpl) findViewObject("DepartmentsVO2");
    }

    /**
     * Container's getter for JobVO1.
     * @return JobVO1
     */
    public ViewObjectImpl getJobVO1() {
        return (ViewObjectImpl) findViewObject("JobVO1");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkLink1");
    }

    /**
     * Container's getter for DeptMgrFkLink1.
     * @return DeptMgrFkLink1
     */
    public ViewLinkImpl getDeptMgrFkLink1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkLink1");
    }

    @Override
    public void create() {
//        BindingContainer bc = BindingContext.getCurrent().getCurrentBindingsEntry();
//        OperationBinding ob = bc.getOperationBinding("CreateInsert");
//        ob.execute();
    }
}

