package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 03 13:18:32 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void create();
}

